plugins:
  composer_title_components:
    client: true
    type: list
    default: ''
    choices:
      - similar-titles
      - topic-type
  composer_topic_types:
    client: true
    type: list
    default: ''
    choices:
     - question
     - rating
     - event
     - general
  composer_override_shortcut:
    client: true
    default: true
